### ISSUE TITLE
issue with locked_next_gw

### ISSUE THREAD

**Issue by karljayb** [sertalpbilal/FPL-Optimization-Tools#27]
I think since the latest commit that locked_next_gw is broken? 

For example, try to lock Haaland 351 and you get the following error from line 217 in multi_period_dev.py:
Traceback (most recent call last):
  multi_period_dev.py", line 217, in prep_data
    locked_next_gw = [int(i[0]) for i in options.get('locked_next_gw', [])]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
                          ~^^^
TypeError: 'int' object is not subscriptable

**Comment by karljayb** [comment]
I am closing this as it has come to my attention that the syntax should be locked_next_gw": [[351, 1]] ['player_id','gw']. This works.

**Comment by sertalpbilal** [comment]
I will unify the parameter, and fix the syntax in Readme file.
