### ISSUE TITLE
Tutorial 2 Single Period

### ISSUE THREAD

**Issue by ZeNoonan** [sertalpbilal/FPL-Optimization-Tools#7]
Hi Sertalp, hope you are well.  I am trying to re-create Tutorial 2 Single Period notebook in a python file.  All good up until cell 32 
![image](https://user-images.githubusercontent.com/52298829/166104980-0abfb252-78eb-4124-b696-c60a07422b46.png)
which is the !{command} line which I cannot create in the python file.  Any help would be much appreciated.  Basically the 'solution_sp.txt' file is not being created, if I could replicate the !{command} in the python file, I would be in business!  I'm thinking I need to explicitly call the solve() function and have it write the solution to a text file, something like that?  Your work is amazing, am very grateful that you share it on github.  Darragh

**Comment by sertalpbilal** [comment]
You need to run it using 
> import os
> os.system("cbc ...")
More info here
https://stackabuse.com/executing-shell-commands-with-python/

**Comment by ZeNoonan** [comment]
Thanks Sertalp, really appreciate you getting back.  
I ran os.system('cbc single_period.mps solve solu solution_sp.txt') and it didn't work; I will look at the shell commands info you sent, thank you for that!

**Comment by sertalpbilal** [comment]
Do you see single_period.mps generated in your directory? If so, try running the command in terminal/command prompt as

``` shell
cbc single_period.mps solve
```

My guess is, either CBC is not in your path, or perhaps MPS file didn't get generated.

**Comment by ZeNoonan** [comment]
Yes looks like 'single_period.mps' file generated fine as I can see the file and it's 633KB.  I ran cbc single_period.mps solve in the terminal and it said cbc was not recognised.  I checked your notebooks and i didn't see cbc being imported as a package.  I had a look at downloading cbc (e.g. cbcpy on PyPi), but not sure i'm going down the right route, as your notebook ran fine without installing cbc.  So it must be a path issue, don't know, sorry about this!

**Comment by sertalpbilal** [comment]
CBC can be downloaded separately, and you can add its absolute path to your PATH environment variable. 
https://github.com/coin-or/Cbc/releases/tag/releases%2F2.10.8
Just download the file (based on your operating system, for Windows it should be `Cbc-releases.2.10.8-x86_64-w64-mingw64.zip`) unzip it and you will see a `bin` directory in it. Add its absolute path to your PATH, and `cbc` command should work fine. Let me know if you get stuck.

**Comment by ZeNoonan** [comment]
It worked thanks!  I put the single_period.mps file in the bin directory, navigated to that directory on the terminal and it worked!  Nice to see the output :-)
