### ISSUE TITLE
[Bug] decision_support.py does not work to generate alternative solutions

### ISSUE THREAD

**Issue by digernes** [sertalpbilal/FPL-Optimization-Tools#8]
Running the decision_support.py produces an error. 

## Expected Behavior
Expect similar behaviour to [the tutorial video on sertalp's channel](https://www.youtube.com/watch?v=4_ac7qEcts0), producing several alternative solutions.

## Current Behavior
Throws an error. First related to updated CSV format, but after changing the `[5]` in line 25 to a `[6]`, a new error comes up:

```
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/ds_h1_GZ2WX.mps'
```

Code likely left a bit behind/not maintained. 

## Steps to Reproduce
You will likely have to change horizon first (in main function). 
1. `cd src`
2. `python .\decision_support.py`

## Context 
Generating alternative solutions is a very useful and powerful feature in the optimizer, and makes it easier to use it as a guiding tool instead of a machine that gives out only one answer.

**Comment by sertalpbilal** [comment]
Thanks for reporting @digernes I will have a look at it. Code is not maintained a while, that is right. Either it needs a touch up or we can merge it with `multi_period` codes for simplicity.

**Comment by sertalpbilal** [comment]
Update on this, have not made any progress yet, but it is the next item in the list.

**Comment by sertalpbilal** [comment]
I have started moving key functionality of `decision_support` to `multi_period_dev` and currently offer a way to produce alternative solutions. Feel free to open a new issue if there is a specific parameter you want to use.
